import json
import re

from models import get_correction_model
from config import (
    TYPE_LABEL_TO_VALUE,
    VALID_TYPES,
    JSON_FIELDS,
    ICONS,
    VIDEOGAME_PLATFORMS,
    MOVIE_FORMATS
)
from identification import format_identification_result
from telegram import send_telegram_message


import re


def parse_identification_message(text: str) -> dict:
    """
    Parse an identification message generated by the bot.

    Example input:

        🎮 Devil May Cry 2

        Type: Videogame
        Platform: Unknown

    Returns:

        {
            "type": "game",
            "title": "Devil May Cry 2",
            "platform": "Unknown",
        }
    """

    # -------------------------------------------------
    # Title
    # -------------------------------------------------

    title_match = re.search(
        r"^(?:🎬|🎮|❓)\s*(.+?)\s*$",
        text,
        re.MULTILINE,
    )

    title = (
        title_match.group(1).strip()
        if title_match
        else "Unknown"
    )

    # -------------------------------------------------
    # Type
    # -------------------------------------------------

    type_match = re.search(
        r"^Type:\s*(.+?)\s*$",
        text,
        re.IGNORECASE | re.MULTILINE,
    )

    raw_type = (
        type_match.group(1).strip().lower()
        if type_match
        else "unknown"
    )

    media_type = TYPE_LABEL_TO_VALUE.get(
        raw_type,
        raw_type,
    )

    if media_type not in VALID_TYPES:
        media_type = "unknown"

    # -------------------------------------------------
    # Platform / Format
    # -------------------------------------------------

    platform_match = re.search(
        r"^(?:Platform|Format):\s*(.+?)\s*$",
        text,
        re.IGNORECASE | re.MULTILINE,
    )

    platform = (
        platform_match.group(1).strip()
        if platform_match
        else "Unknown"
    )

    return {
        "type": media_type,
        "title": title,
        "platform": platform,
    }


def invoke_model(messages: list) -> str:
    model, tokenizer = get_correction_model()

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(
        text,
        return_tensors="pt",
    )

    outputs = model.generate(
        **inputs,
        max_new_tokens=80,
        do_sample=False,
        temperature=None,
        top_p=None,
        top_k=None,
    )

    generated = outputs[0][
        inputs["input_ids"].shape[1]:
    ]

    return tokenizer.decode(
        generated,
        skip_special_tokens=True,
    ).strip()

def create_messages(system_prompt, user_prompt):
    return [
        {
            "role": "system",
            "content": system_prompt,
        },
        {
            "role": "user",
            "content": user_prompt,
        },
    ]


def correct_identification(
    previous_result: dict,
    correction_text: str,
) -> dict:

    system_prompt = (
        "You extract corrections from the user's message.\n\n"

        "Check each field independently:\n"
        "- TYPE: whether the user says it is a movie or a game\n"
        "- TITLE: whether the user changes the title\n"
        "- PLATFORM: whether the user changes the platform or format\n\n"

        "Only return fields that the user explicitly changes.\n"
        "Do not return unchanged fields.\n"
        "Do not infer corrections.\n"
        "Do not modify values that the user provides.\n"
        "Do not expand or normalize titles.\n"
        "Return ONLY valid JSON.\n\n"

        "TYPE must be either 'movie' or 'game'.\n\n"

        "Example:\n"
        'Current identification: '
        '{"type":"game","title":"Devil May Cry 2","platform":"PlayStation 2"}\n'
        'User correction: "Actually it is Devil May Cry 3"\n'
        'Output: {"title":"Devil May Cry 3"}\n\n'

        'Example:\n'
        'Current identification: '
        '{"type":"game","title":"Devil May Cry 2","platform":"PlayStation 2"}\n'
        'User correction: "It is a movie"\n'
        'Output: {"type":"movie"}\n\n'

        'Example:\n'
        'Current identification: '
        '{"type":"game","title":"Devil May Cry 2","platform":"PlayStation 2"}\n'
        'User correction: "The platform is Xbox"\n'
        'Output: {"platform":"Xbox"}'
    )

    user_prompt = (
        f"Current identification:\n"
        f"{json.dumps(previous_result, ensure_ascii=False)}\n\n"
        f"User correction:\n"
        f"{correction_text}"
    )

    messages = create_messages(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
    )

    raw_answer = invoke_model(messages=messages)

    print(
        f"Correction model raw answer: {raw_answer}"
    )

    candidates = re.findall(
        r"\{.*?\}",
        raw_answer,
        re.DOTALL,
    )

    for candidate in candidates:
        try:
            parsed = json.loads(candidate)

            if isinstance(parsed, dict):
                return parsed

        except json.JSONDecodeError:
            continue

    print(
        "Could not parse correction JSON: "
        "no valid JSON object found"
    )

    return {}

def identify_platform(platform: str, type: str) -> str:
    if type == "game":
        available_platforms = VIDEOGAME_PLATFORMS
    elif type == "movie":
        available_platforms = MOVIE_FORMATS
    else:
        return platform

    normalized = platform.strip().lower()

    # Exact match
    for available in available_platforms:
        if normalized == available.lower():
            return available

    # Common aliases
    aliases = {
        "gc": "GameCube",
        "ngc": "GameCube",
        "gamecube": "GameCube",
        "ps1": "PlayStation 1",
        "ps": "PlayStation",
        "ps2": "PlayStation 2",
        "ps3": "PlayStation 3",
        "ps4": "PlayStation 4",
        "ps5": "PlayStation 5",
        "psp": "PlayStation Portable",
        "psv": "PlayStation Vita",
        "vita": "PlayStation Vita",
        "nds": "Nintendo DS",
        "ds": "Nintendo DS",
        "3ds": "Nintendo 3DS",
        "wii": "Wii",
        "wii u": "Wii U",
        "switch": "Nintendo Switch",
        "n64": "Nintendo 64",
        "snes": "Super Nintendo Entertainment System",
        "nes": "Nintendo Entertainment System",
        "gb": "Game Boy",
        "gba": "Game Boy Advance",
        "gbc": "Game Boy Color",
    }

    alias = aliases.get(normalized)

    if alias:
        for available in available_platforms:
            if available.lower() == alias.lower():
                return available

    system_prompt = (
        "You identify the correct platform or format from a list of "
        "allowed values.\n\n"

        "The user provided a platform or format name. Your task is to "
        "map it to the closest matching value from the allowed list.\n\n"

        "Rules:\n"
        "- Return EXACTLY one value from the allowed list.\n"
        "- Do not invent new values.\n"
        "- Do not explain your answer.\n"
        "- Think of common abbreviations like GC for GameCube, PSV for PS Vita, NDS for Nintendo DS...\n"
        "- Return only the selected value.\n\n"

        f"Allowed values:\n{json.dumps(available_platforms, ensure_ascii=False)}"
    )

    user_prompt = (
        f"User platform or format: {platform}\n\n"
        "Return the matching value from the allowed list."
    )

    messages = create_messages(system_prompt, user_prompt)
    response = invoke_model(messages)

    return response

def handle_correction(
    chat_id: str,
    message_id: str,
    correction_text: str,
    reply_to_message_text: str,
):

    previous_result = parse_identification_message(
        reply_to_message_text
    )

    print(
        "Previous identification:",
        json.dumps(
            previous_result,
            ensure_ascii=False,
        ),
    )

    print(
        "User correction:",
        repr(correction_text),
    )

    change_fields = correct_identification(
        previous_result=previous_result,
        correction_text=correction_text,
    )

    # Normalize platform only if the user actually changed it
    if "platform" in change_fields:
        change_fields["platform"] = identify_platform(
            change_fields["platform"],
            change_fields.get(
                "type",
                previous_result["type"],
            ),
        )

    # Apply corrections to the previous identification
    corrected_result = {
        **previous_result,
        **change_fields,
    }

    response_text = format_identification_result(
        corrected_result
    )

    sent_message = send_telegram_message(
        chat_id=chat_id,
        text=response_text,
        reply_to_message_id=message_id,
        include_buttons=True,
    )

    print(
        "Corrected identification:",
        json.dumps(
            corrected_result,
            ensure_ascii=False,
        ),
    )

    print(
        "Corrected result sent to Telegram. "
        f"Message ID: "
        f"{sent_message['result']['message_id']}"
    )